<a href="https://colab.research.google.com/github/aaryaa12/data_hider/blob/main/Copy_of_intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to num py

In [ ]:
# importing numpy
import numpy as np


In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [ ]:
# lets create an array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# creaye an array with different values
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7,  8,  9])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# multidimaensional array
np.zeros( (5, 2) )

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones ( (3, 3) )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.array ([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[1, 1] = 50

In [ ]:
b

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [ ]:
# random number generation
np.random.seed(100)
np.random.rand(5, 2)

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613],
       [0.00471886, 0.12156912],
       [0.67074908, 0.82585276],
       [0.13670659, 0.57509333]])

In [ ]:
# random numbers following normal distribution
np.random.randn (5, 2)

array([[-0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517],
       [-0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ],
       [ 0.73100034,  1.36155613]])

In [ ]:
np.random.randint (low=0, high=100, size=(5, 2))

array([[53, 68],
       [50, 91],
       [91, 83],
       [53, 78],
       [ 0, 13]])

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a.std ()

np.float64(1.4142135623730951)

In [ ]:
a.min ()

np.int64(0)

In [ ]:
a.max ()

np.int64(4)

In [ ]:
a.sum()

np.int64(10)